Enable only Python 3.7, 3.9 and splunk 8.2 and 9.4

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -10,11 +10,11 @@ jobs:
         os: [ubuntu-latest]
         python-version:
           - 3.7
-          # - 3.9
+          - 3.9
           # - 3.13
         splunk-version:
           - "8.2"
-          # - "9.3"
+          - "9.3"
           # - "9.4"
           # - "latest"
       fail-fast: false
@@ -31,15 +31,15 @@ jobs:
           python-version: ${{ matrix.python-version }}
       - name: Install dependencies
         run: type -a python && python -m pip install tox
-      - name: Run Docker health check
-        # This probably does nothing
-        run: |
-          timeout 30s make wait_up
-          if [ $? -eq 124 ]; then
-            echo "Splunk failed to start within 30 seconds."
-            docker compose logs
-            exit 1
-          fi
+      # - name: Run Docker health check
+      #   # This probably solves nothing
+      #   run: |
+      #     timeout 30s make wait_up
+      #     if [ $? -eq 124 ]; then
+      #       echo "Splunk failed to start within 30 seconds."
+      #       docker compose logs
+      #       exit 1
+      #     fi
       - name: Run test suite
         run: type -a python && python -m tox -e py
 # [BJ] I'll uncomment this step after I finish fiddling
